# Setup
setup: multi_task

# Database
train_db_name: NYUD_GeoNet
val_db_name: NYUD_GeoNet
trBatch: 8
valBatch: 8
nworkers: 8

gpu0_bsz: 2

# Optimizer and scheduler
epochs: 20
optimizer: adam
optimizer_kwargs:
  lr: 0.00005
  weight_decay: 0.0001
scheduler: poly


# Model
model: geodepthnet
backbone: hrnet_w48
backbone_kwargs:
  pretrained: False
  dilated: False
head: hrnet


use_guidance: True
use_probability: False
normal_loss: True

guidance_reduce: True
use_gt_depth: False


# Tasks
task_dictionary:
  #    include_semseg: True
  include_depth: True
#  include_normals: True

auxilary_task_dictionary:
  #    include_semseg: True
  include_depth: True
  #    include_edge: True
#  include_normals: True
#    edge_w: 0.95 

